spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/crediya_db
    username: usuario
    password: contrasena
  flyway:
    url: jdbc:postgresql://localhost:5433/crediya_db
    user: usuario
    password: contrasena
