server:
  port: 8080
spring:
  application:
    name: "CrediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/crediya"
    user: "user"
    password: "password"
    pool:
      initial-size: 5
      max-size: 20
  flyway:
    enabled: true
    url: "jdbc:postgresql://localhost:5432/crediya"
    user: "user"
    password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
